destination: _site/
url: "http://127.0.0.1:4000"
baseurl: ""
port: 4000
output: pdf
product: GEO-PORTAL
print_title: GEO-PORTAL
print_subtitle: Predstavitev
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: gp_sidebar
